name: syncvault
description: A new Flutter project.

publish_to: "none"

version: 0.9.2

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ^3.35.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: ^5.9.0
  file_picker: ^10.3.3
  flutter_hooks: ^0.21.3
  flutter_svg: ^2.2.1
  flutter_web_auth_2: ^4.1.0
  fpdart: ^1.1.1
  freezed_annotation: ^3.1.0
  hooks_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  json_annotation: ^4.9.0
  watcher: ^1.1.4
  window_manager: ^0.5.1
  sentry_flutter: ^9.6.0
  url_launcher: ^6.3.2
  permission_handler: ^12.0.1
  flutter_dotenv: ^6.0.0
  injectable: ^2.5.2
  get_it: ^8.2.0
  logger: ^2.6.2
  flutter_fancy_tree_view: ^1.6.0
  path_provider: ^2.1.5
  introduction_screen: ^4.0.0
  archive: ^4.0.7
  glob: ^2.1.3
  hive_ce: ^2.14.0
  hive_ce_flutter: ^2.3.2
  ini_v2:
    git:
      url: https://github.com/dhzdhd/ini_v2.git
      ref: 02e44bb
  animated_tree_view: ^2.3.0
  googleapis: ^15.0.0
  google_sign_in: ^7.2.0
  oauth2: ^2.0.3
  googleapis_auth: ^2.0.0
  google_fonts: ^6.3.2
  tray_manager: ^0.5.1
  fl_nodes: ^0.5.0+1
  workmanager:
    git:
      url: https://github.com/fluttercommunity/flutter_workmanager.git
      path: workmanager
      ref: 4ce065135dc1b91fee918f81596b42a56850391d
  flutter_local_notifications: ^19.4.2
  hashlib: ^2.2.0
  launch_at_startup: ^0.5.1
  package_info_plus: ^9.0.0
  path: ^1.9.1
  http: ^1.5.0
  connectivity_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  riverpod_lint: ^2.6.5
  riverpod_generator: ^2.6.5
  flutter_launcher_icons: ^0.14.3
  injectable_generator: ^2.7.0
  hive_ce_generator: ^1.9.2

flutter:
  uses-material-design: true
  generate: true

  shaders:
    - packages/fl_nodes/shaders/grid.frag

  assets:
    - assets/images/
    - assets/logos/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter.ttf
