name: syncvault
description: A new Flutter project.

publish_to: 'none'

version: 0.3.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: ^5.3.3
  file_picker: ^6.1.1
  flutter_hooks: ^0.20.3
  flutter_svg: ^2.0.9
  flutter_web_auth_2: ^2.1.4
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.4.6
  riverpod_annotation: ^2.3.1
  json_annotation: ^4.8.1
  system_tray: ^2.0.3
  watcher: ^1.1.0
  window_manager: ^0.3.7
  sentry_flutter: ^7.12.0
  url_launcher: ^6.2.1
  workmanager: ^0.5.2
  permission_handler: ^11.0.1
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.3.4
  json_serializable: ^6.7.0
  custom_lint: ^0.4.0
  riverpod_lint: ^1.3.2
  riverpod_generator: ^2.2.3

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/logos/
    - assets/icons/
    - .env
