name: syncvault
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 0.2.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dio: ^5.1.2
  file_picker: ^5.3.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.6
  flutter_web_auth_2: ^2.1.4
  fpdart: ^0.6.0
  freezed_annotation: ^2.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.3.6
  json_annotation: ^4.8.1
  system_tray: ^2.0.3
  watcher: ^1.1.0
  window_manager: ^0.3.4
  sentry_flutter: ^7.7.0
  url_launcher: ^6.1.11
  workmanager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.4
  freezed: ^2.3.4
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/images/
    - assets/logos/
    - assets/icons/
