name: syncvault
description: A new Flutter project.

publish_to: 'none'

version: 0.4.1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ^3.22.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: ^5.4.2
  file_picker: ^8.0.5
  flutter_hooks: ^0.20.4
  flutter_svg: ^2.0.9
  flutter_web_auth_2: ^3.1.1
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hooks_riverpod: ^3.0.0-dev.3
  riverpod_annotation: ^3.0.0-dev.3
  json_annotation: ^4.9.0
  system_tray: ^2.0.3
  watcher: ^1.1.0
  window_manager: ^0.3.7
  sentry_flutter: ^8.2.0
  url_launcher: ^6.3.0
  workmanager: ^0.5.2
  permission_handler: ^11.3.1
  flutter_dotenv: ^5.1.0
  injectable: ^2.3.2
  get_it: ^7.6.7
  logger: ^2.0.2+1
  flutter_fancy_tree_view: ^1.4.1
  path_provider: ^2.1.3
  introduction_screen: ^3.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  freezed: ^2.3.4
  json_serializable: ^6.7.0
  custom_lint: ^0.5.8
  riverpod_lint: ^3.0.0-dev.4
  riverpod_generator: ^3.0.0-dev.11
  flutter_launcher_icons: ^0.13.1
  injectable_generator: ^2.4.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/logos/
    - assets/icons/
    - .env
