name: syncvault
description: A new Flutter project.

publish_to: 'none'

version: 0.7.4

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: ^3.27.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: ^5.7.0
  file_picker: 8.1.4
  flutter_hooks: ^0.20.4
  flutter_svg: ^2.0.16
  flutter_web_auth_2: ^4.1.0
  fpdart: ^1.1.1
  freezed_annotation: ^2.4.4
  hooks_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  json_annotation: ^4.9.0
  system_tray: ^2.0.3
  watcher: ^1.1.0
  window_manager: ^0.4.3
  sentry_flutter: ^8.11.0
  url_launcher: ^6.3.1
  workmanager: ^0.5.2
  permission_handler: ^11.3.1
  flutter_dotenv: ^5.2.1
  injectable: ^2.5.0
  get_it: ^8.0.3
  logger: ^2.5.0
  flutter_fancy_tree_view: ^1.4.1
  path_provider: ^2.1.5
  introduction_screen: ^3.1.14
  archive: ^4.0.1
  glob: ^2.1.2
  hive_ce: ^2.8.0+2
  hive_ce_flutter: ^2.1.0
  ini_v2:
    git:
      url: https://github.com/dhzdhd/ini_v2.git
      ref: 02e44bb
  animated_tree_view: ^2.1.0
  googleapis: ^13.2.0
  google_sign_in: ^6.2.2
  oauth2: ^2.0.3
  googleapis_auth: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  freezed: ^2.3.4
  json_serializable: ^6.7.0
  custom_lint: ^0.6.10
  riverpod_lint: ^2.6.1
  riverpod_generator: ^2.6.1
  flutter_launcher_icons: ^0.13.1
  injectable_generator: ^2.4.1
  hive_ce_generator: ^1.8.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/logos/
    - assets/icons/
