import 'package:flutter/material.dart';

const lightColorScheme = ColorScheme(
  brightness: Brightness.light,
  primary: Color(0xFF006875),
  onPrimary: Color(0xFFFFFFFF),
  primaryContainer: Color(0xFF9CEFFF),
  onPrimaryContainer: Color(0xFF001F24),
  secondary: Color(0xFF4A6267),
  onSecondary: Color(0xFFFFFFFF),
  secondaryContainer: Color(0xFFCDE7ED),
  onSecondaryContainer: Color(0xFF051F23),
  tertiary: Color(0xFF535D7E),
  onTertiary: Color(0xFFFFFFFF),
  tertiaryContainer: Color(0xFFDAE2FF),
  onTertiaryContainer: Color(0xFF0F1A37),
  error: Color(0xFFBA1A1A),
  errorContainer: Color(0xFFFFDAD6),
  onError: Color(0xFFFFFFFF),
  onErrorContainer: Color(0xFF410002),
  background: Color(0xFFFBFCFD),
  onBackground: Color(0xFF191C1D),
  surface: Color(0xFFFBFCFD),
  onSurface: Color(0xFF191C1D),
  surfaceVariant: Color(0xFFDBE4E6),
  onSurfaceVariant: Color(0xFF3F484A),
  outline: Color(0xFF6F797B),
  onInverseSurface: Color(0xFFEFF1F2),
  inverseSurface: Color(0xFF2E3132),
  inversePrimary: Color(0xFF50D8ED),
  shadow: Color(0xFF000000),
  surfaceTint: Color(0xFF006875),
  outlineVariant: Color(0xFFBFC8CA),
  scrim: Color(0xFF000000),
);

const darkColorScheme = ColorScheme(
  brightness: Brightness.dark,
  primary: Color(0xFF50D8ED),
  onPrimary: Color(0xFF00363D),
  primaryContainer: Color(0xFF004F58),
  onPrimaryContainer: Color(0xFF9CEFFF),
  secondary: Color(0xFFB1CBD0),
  onSecondary: Color(0xFF1C3438),
  secondaryContainer: Color(0xFF334B4F),
  onSecondaryContainer: Color(0xFFCDE7ED),
  tertiary: Color(0xFFBBC5EA),
  onTertiary: Color(0xFF252F4D),
  tertiaryContainer: Color(0xFF3B4665),
  onTertiaryContainer: Color(0xFFDAE2FF),
  error: Color(0xFFFFB4AB),
  errorContainer: Color(0xFF93000A),
  onError: Color(0xFF690005),
  onErrorContainer: Color(0xFFFFDAD6),
  background: Color(0xFF191C1D),
  onBackground: Color(0xFFE1E3E3),
  surface: Color(0xFF191C1D),
  onSurface: Color(0xFFE1E3E3),
  surfaceVariant: Color(0xFF3F484A),
  onSurfaceVariant: Color(0xFFBFC8CA),
  outline: Color(0xFF899294),
  onInverseSurface: Color(0xFF191C1D),
  inverseSurface: Color(0xFFE1E3E3),
  inversePrimary: Color(0xFF006875),
  shadow: Color(0xFF000000),
  surfaceTint: Color(0xFF50D8ED),
  outlineVariant: Color(0xFF3F484A),
  scrim: Color(0xFF000000),
);

final lightTheme = ThemeData(
  brightness: Brightness.light,
  useMaterial3: true,
  colorScheme: lightColorScheme,
  textTheme: const TextTheme(),
);
final darkTheme = ThemeData(
  brightness: Brightness.dark,
  useMaterial3: true,
  colorScheme: darkColorScheme,
  textTheme: const TextTheme(),
);
