icon: assets/icons/logo.png
summary: A drive sync application to sync your files to the cloud.
group: Application/Utility
vendor: dhzdhd
packager: dhzdhd
packagerEmail: dhzdhd@proton.me
license: GPLv3
url: https://github.com/dhzdhd/SyncVault/

display_name: SyncVault

keywords:
  - Application
  - Cloud
  - Sync

generic_name: SyncVault

categories:
  - Sync
  - Cloud

startup_notify: true
