app_id: 5E599538-42E1-4526-E579-EF059F21A55E
publisher: dhzdhd
publisher_url: https://github.com/leanflutter/SyncVault
display_name: SyncVault
create_desktop_icon: true
# See: https://jrsoftware.org/ishelp/index.php?topic=setup_defaultdirname
# install_dir_name: "D:\\HELLO-WORLD"
locales:
  - en
