name: Build and Release app

on:
  push:
    tags: ["v*.*.*"]

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Build Android apps
        run: |
          flutter pub get
          flutter build apk --split-per-abi
          flutter build appbundle

      - name: Save android packages
        uses: actions/upload-artifact@v4
        with:
          name: android
          path: |
            build/app/outputs/flutter-apk/*
            build/app/outputs/bundle/release/*

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Build Windows
        run: |
          flutter config --enable-windows-desktop
          flutter pub get
          flutter build windows --release

      - name: Save Windows app
        uses: actions/upload-artifact@v4
        with:
          name: win
          path: build\windows\x64\runner\Release\*

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Build Linux
        run: |
          flutter config --enable-linux-desktop
          flutter pub get
          flutter build linux --release

      - name: Save Linux bundle
        uses: actions/upload-artifact@v4
        with:
          name: linux
          path: |
            build/linux/x64/release/bundle/*

  release:
    runs-on: ubuntu-latest
    needs: [build-android, build-windows, build-linux]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get all build outputs
        uses: actions/download-artifact@v4
        with:
          path: exec/

      - name: Zip Windows programs
        run: 7z a -tZip ExCode-win.zip exec/win

      - name: Zip Linux bundle
        run: tar -czvf Excode-linux.tar.gz exec/linux

      - name: Display structure of downloaded files
        run: tree exec/

      - name: Create release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: SyncVault
          prerelease: true
          generate_release_notes: true
          files: |
            exec/android/bundle/release/app-release.aab
            exec/android/flutter-apk/*
            ExCode-win.zip
            ExCode-linux.tar.gz
            exec/win/ExCode.msix
          body_path: CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_REPOSITORY: dhzdhd/SyncVault
