name: Build and Release app

on:
  push:
    branches: [stable]

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Create env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Build Android apps
        run: |
          flutter pub get
          flutter build apk --split-per-abi
          flutter build appbundle

      - name: Save android packages
        uses: actions/upload-artifact@v3
        with:
          name: android
          path: |
            build/app/outputs/flutter-apk/*
            build/app/outputs/bundle/release/*

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Create env file
        run: |
          Write-Output "${{ secrets.ENV_FILE }}" | Out-File .env

      - name: Build Windows
        run: |
          flutter config --enable-windows-desktop
          flutter pub get
          flutter build windows

      - name: Save Windows app
        uses: actions/upload-artifact@v3
        with:
          name: win
          path: build\windows\runner\Release\*

  release:
    runs-on: ubuntu-latest
    needs: [build-android, build-windows]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get all build outputs
        uses: actions/download-artifact@v3
        with:
          path: exec/

      - name: Zip Windows programs
        run: 7z a -tZip ExCode-win.zip exec/win

      - name: Display structure of downloaded files
        run: tree exec/

      - name: Create release
        uses: softprops/action-gh-release@v1
        #// if: startsWith(github.ref, 'refs/tags/')
        with:
          name: SyncVault
          tag_name: v0.3.0
          prerelease: true
          generate_release_notes: true
          files: |
            exec/android/bundle/release/app-release.aab
            exec/android/flutter-apk/*
            ExCode-win.zip
            exec/win/ExCode.msix
          body_path: CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_REPOSITORY: dhzdhd/SyncVault
