name: Fastforge - Build and Release app

on:
  push:
    tags: ["v*.*.*"]

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Install Fastforge deps
        run: |
          choco install innosetup -y
          
      - name: Enable Windows
        run: |
          flutter config --enable-windows-desktop
          flutter pub get

      - name: Install Fastforge
        run: dart pub global activate fastforge

      - name: Build and export
        run: fastforge release --name windows

      - name: Debug tree
        run: tree dist/

      - name: Save Windows bundle
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: dist/**/*

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Install devtools
        run: |
          sudo apt-get update -y
          sudo apt-get install -y curl git unzip xz-utils zip libglu1-mesa
          sudo apt-get install clang cmake git ninja-build pkg-config libgtk-3-dev liblzma-dev libstdc++-12-dev
          sudo apt-get install libwebkit2gtk-4.1-dev
          sudo apt-get install curl libcurl4-openssl-dev
          sudo apt-get install libayatana-appindicator3-dev

      - name: Install Fastforge deps
        run: |
          sudo apt-get install rpm patchelf locate

      - name: Enable Linux
        run: |
          flutter config --enable-linux-desktop
          flutter pub get

      - name: Install Fastforge
        run: dart pub global activate fastforge

      - name: Build and export
        run: fastforge release --name linux

      - name: Debug tree
        run: tree dist/
      
      - name: Save Linux bundle
        uses: actions/upload-artifact@v4
        with:
          name: linux
          path: dist/**/*
  
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '24'

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods

      - name: Install Fastforge deps
        run: |
          brew install p7zip
          brew install tree
          npm install -g appdmg

      - name: Enable macOS
        run: |
          flutter config --enable-macos-desktop
          flutter pub get
          pod install --project-directory=macos
        
      - name: Install Fastforge
        run: dart pub global activate fastforge

      - name: Build and export
        run: fastforge release --name macos

      - name: Debug tree
        run: tree dist/

      - name: Save macOS bundle
        uses: actions/upload-artifact@v4
        with:
          name: macos
          path: dist/**/*

  release:
    runs-on: ubuntu-latest
    needs: [build-windows, build-linux, build-macos]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get all build outputs
        uses: actions/download-artifact@v4
        with:
          path: exec/

      - name: Display structure of downloaded files
        run: tree exec/

      - name: Create release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: SyncVault
          prerelease: true
          generate_release_notes: true
          files: |
            exec/*
          body_path: CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_REPOSITORY: dhzdhd/SyncVault
