name: Update CocoaPods

on:
  workflow_dispatch:
  schedule:
    # Run weekly on Monday at 00:00 UTC
    - cron: '0 0 * * 1'

jobs:
  update-pods:
    runs-on: macos-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          
      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          
      - name: Update CocoaPods repo
        run: |
          pod repo update
          
      - name: Flutter pub get
        run: flutter pub get
        
      # - name: Update iOS Pods
      #   run: |
      #     cd ios
      #     pod install --repo-update
          
      - name: Update macOS Pods
        run: |
          cd macos
          pod install --repo-update
          
      - name: Check for changes
        id: check_changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Create Pull Request
        if: steps.check_changes.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Update CocoaPods dependencies'
          title: 'Update CocoaPods dependencies'
          body: |
            This PR updates the CocoaPods dependencies for iOS and macOS.
            
            Updated files:
            - `ios/Podfile.lock`
            - `macos/Podfile.lock`
            
            Changes were automatically generated by the Update CocoaPods workflow
          branch: chore/update-cocoapods
          delete-branch: true
          maintainer-can-modify: true
